### ISSUE TITLE
NameError: name 'Ranger' is not defined

### ISSUE THREAD

**Issue by bvkini** [shashist/recsys-rl#1]
Hi, I was trying to experiment with https://github.com/shashist/recsys-rl
However, I'm getting: NameError: name 'Ranger' is not defined
I installed ranger package, that didn't help either.
Any help is highly appreciated.

**Comment by sepilqi** [comment]
```bash
git clone https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
cd Ranger-Deep-Learning-Optimizer
pip install -e . 
```

**Comment by sepilqi** [comment]
@bvkini it's not a standard package from `pip install ranger`. The correct one is https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

**Comment by sepilqi** [comment]
or `pip install git+https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer`

**Comment by WinnieZM** [comment]
@sepilqi @bvkini Hello！Can you open the folder of Part 4? If it can be opened, can you share the folder?

**Comment by shashist** [comment]
Hi guys!

Last year Ranger updated installation and importing. So I updated requirements.txt and line with import.
Now code should be fully reproducible.

Wish you a Happy New Year!
