### ISSUE TITLE
Hello Author! I would like to ask if the code does not include cuda acceleration? I'm running very slow!

### ISSUE THREAD

**Issue by Daming0508** [shashist/recsys-rl#2]

**Comment by WinnieZM** [comment]
@Daming0508 Hello！Can you open the folder of Part 4? If it can be opened, can you share the folder?

**Comment by shashist** [comment]
Hi @Daming0508 and thank you for you comment! 
Code uses mostly linear layers, so time with and w/o cuda is pretty the same!
Can advise you to increase cpu count.

Btw, Happy New Year!
